import google.generativeai as genai
import os 
import sys
import logging

# Adding project root to Python path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import Config

class GeminiReportGenerator:
    """
    Gemini model for generating student focus reports.
    """
    def __init__(self, model_name: str = "gemini-1.5-flash"):
        """
        Initialize the gemini model using config

        Args:
            model_name (str): The name of the Gemini model to use.
        """
        self.model_name = model_name
        self.logger = logging.getLogger(__name__)

        # Read key from Config, then fall back to env vars commonly used
        api_key = getattr(Config, "GEMINI_API_KEY", None) or \
                  getattr(Config, "Gemini_API_KEY", None) or \
                  os.getenv("GEMINI_API_KEY") or \
                  os.getenv("GOOGLE_API_KEY")

        if not api_key:
            # Helpful log but doesn't leak the key
            self.logger.error("Gemini API key not found in Config or environment.")
            raise RuntimeError(
                "Missing Gemini API key. Set GEMINI_API_KEY (or GOOGLE_API_KEY) in the environment."
            )

        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel(self.model_name)

    def generate_report(self, prompt: str, temperature: float = 0.7) -> dict:
        """
        Generate a report using gemini model.

        Args:
            prompt(str): The formatted prompt from report_prompt.py.
            temperature(float): controls randomness (0.0 to 1.0)

            Returns:
                dict: contains success status and report text.
        """
        try:
            # Configure generation
            generation_config = genai.types.GenerationConfig(
                temperature=temperature,
                max_output_tokens=2000,  
                top_p=0.9,
                top_k=40
            )

            # Generate response
            response = self.model.generate_content(
                prompt,
                generation_config=generation_config
            )

            # Debug logging
            print(f"🤖 Gemini Response received. Length: {len(response.text) if response.text else 0}")
            
            if response.text:
                return {
                    "success": True,
                    "report": response.text.strip()
                }
            else:
                return {
                    "success": False,
                    "error": "No content generated by Gemini"
                }
        except Exception as e:
            self.logger.error(f"Error generating report: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    def test_connection(self) -> bool:
        """
        Test if the Gemini model is reachable.

        Returns:
            bool: True if connection is successful, False otherwise.
        """
        try:
            self.model.generate_content("Test connection")
            return True
        except Exception as e:
            self.logger.error(f"Connection test failed: {str(e)}")
            return False
        
